# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_permission',
            name='permission_id',
            field=models.IntegerField(blank=True),
        ),
    ]
