# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20151226_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationresponse',
            unique_together=set([]),
        ),
    ]
