# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20151222_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
