# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_user_cookie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie_id',
        ),
    ]
