# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_group_notification_queue_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='notification_queue',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='percentage',
        ),
    ]
