# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20151223_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_permission',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
