# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_user_cookie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ask', models.BooleanField(default=False)),
            ],
        ),
    ]
