# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20151216_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_id', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification_Queue',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='url',
            new_name='target_url',
        ),
    ]
