# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20160125_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='push_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
