# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20151227_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
