# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20151224_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='website',
            field=models.CharField(default='localhost:4000', max_length=50),
            preserve_default=False,
        ),
    ]
