# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20151226_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='website',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='website',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='group',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Client'),
            preserve_default=False,
        ),
    ]
