# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_ask_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_id', models.IntegerField()),
            ],
        ),
    ]
