# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20151217_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionresponse',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
