# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20151217_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationresponse',
            unique_together=set([('user_id', 'notification_id')]),
        ),
    ]
