# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationresponse',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='notificationresponse',
            name='notification_id',
        ),
    ]
