# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20151226_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationresponse',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Notification'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notificationresponse',
            unique_together=set([('user_id', 'notification')]),
        ),
    ]
