# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20151217_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='push_key',
            field=models.CharField(max_length=200),
        ),
    ]
