# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20151221_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
